### Submission on 20150714

In [1]:
import pandas as pd
#import sklearn as sk
from sklearn.linear_model import LinearRegression

def get_feature_mat(fname):
	#feature engineering in this funciton is applied to both test and train
	df 	= pd.read_csv("./"+fname)
	return(df)

train, test = [get_feature_mat(fname) for fname in ['data/train.csv', 'data/test.csv']]
print('\nSummary of train dataset:\n')
print(train.describe())
print('\nSummary of test dataset:\n')
print(test.describe())

#print(train.columns.values)
#print(test.columns.values)

train_data = train[['season','holiday','workingday','weather','temp','atemp','humidity','windspeed']]
train_cnt, train_casual, train_registered = train[['count']], train[['casual']], train[['registered']]

test_data = test[['season','holiday','workingday','weather','temp','atemp','humidity','windspeed']]
# Fit linear regression model with training data
lr_count = LinearRegression(fit_intercept=True)
lr_count.fit(train_data, train_cnt)

Summary of train dataset:

             season       holiday    workingday       weather         temp  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.00000
mean       2.506614      0.028569      0.680875      1.418427     20.23086
std        1.116174      0.166599      0.466159      0.633839      7.79159
min        1.000000      0.000000      0.000000      1.000000      0.82000
25%        2.000000      0.000000      0.000000      1.000000     13.94000
50%        3.000000      0.000000      1.000000      1.000000     20.50000
75%        4.000000      0.000000      1.000000      2.000000     26.24000
max        4.000000      1.000000      1.000000      4.000000     41.00000

              atemp      humidity     windspeed        casual    registered  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.000000
mean      23.655084     61.886460     12.799395     36.021955    155.552177
std        8.474601     19.245033      8.164537     49.960477    151.039033
min        0.760000      0.000000      0.000000      0.000000      0.000000
25%       16.665000     47.000000      7.001500      4.000000     36.000000
50%       24.240000     62.000000     12.998000     17.000000    118.000000
75%       31.060000     77.000000     16.997900     49.000000    222.000000
max       45.455000    100.000000     56.996900    367.000000    886.000000

              count
count  10886.000000
mean     191.574132
std      181.144454
min        1.000000
25%       42.000000
50%      145.000000
75%      284.000000
max      977.000000

Summary of test dataset:

            season      holiday   workingday      weather         temp  \
count  6493.000000  6493.000000  6493.000000  6493.000000  6493.000000
mean      2.493300     0.029108     0.685815     1.436778    20.620607
std       1.091258     0.168123     0.464226     0.648390     8.059583
min       1.000000     0.000000     0.000000     1.000000     0.820000
25%       2.000000     0.000000     0.000000     1.000000    13.940000
50%       3.000000     0.000000     1.000000     1.000000    21.320000
75%       3.000000     0.000000     1.000000     2.000000    27.060000
max       4.000000     1.000000     1.000000     4.000000    40.180000

             atemp     humidity    windspeed
count  6493.000000  6493.000000  6493.000000
mean     24.012865    64.125212    12.631157
std       8.782741    19.293391     8.250151
min       0.000000    16.000000     0.000000
25%      16.665000    49.000000     7.001500
50%      25.000000    65.000000    11.001400
75%      31.060000    81.000000    16.997900
max      50.000000   100.000000    55.998600

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [2]:
lr_count_pred = lr_count.predict(test_data)
#test.columns.values
result = test[['datetime']]
result.loc[:,'count'] = lr_count_pred
result.loc[:,'count'].loc[result.loc[:,'count'] < 0] = 0
result

/Users/tma/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:249: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/Users/tma/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:415: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/Users/tma/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/tma/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                 datetime       count
0     2011-01-20 00:00:00   96.067443
1     2011-01-20 01:00:00   88.630157
2     2011-01-20 02:00:00   88.630157
3     2011-01-20 03:00:00   92.933464
4     2011-01-20 04:00:00   92.933464
5     2011-01-20 05:00:00   73.770396
6     2011-01-20 06:00:00   67.975840
7     2011-01-20 07:00:00   83.260015
8     2011-01-20 08:00:00   86.370402
9     2011-01-20 09:00:00  104.163795
10    2011-01-20 10:00:00  115.853940
11    2011-01-20 11:00:00  138.263769
12    2011-01-20 12:00:00  157.456795
13    2011-01-20 13:00:00  139.433096
14    2011-01-20 14:00:00  146.752085
15    2011-01-20 15:00:00  155.657027
16    2011-01-20 16:00:00  134.524744
17    2011-01-20 17:00:00  137.251870
18    2011-01-20 18:00:00  100.424770
19    2011-01-20 19:00:00   92.957057
20    2011-01-20 20:00:00   88.585900
21    2011-01-20 21:00:00   81.261702
22    2011-01-20 22:00:00   63.255611
23    2011-01-20 23:00:00   65.589703
24    2011-01-21 00:00:00   50.693350
25    2011-01-21 01:00:00   50.693350
26    2011-01-21 02:00:00   40.936476
27    2011-01-21 03:00:00   22.603253
28    2011-01-21 04:00:00    0.000000
29    2011-01-21 05:00:00   75.346577
...                   ...         ...
6463  2012-12-30 18:00:00  129.374974
6464  2012-12-30 19:00:00  106.148695
6465  2012-12-30 20:00:00  110.057148
6466  2012-12-30 21:00:00   92.011658
6467  2012-12-30 22:00:00   77.085348
6468  2012-12-30 23:00:00   90.870487
6469  2012-12-31 00:00:00   70.141261
6470  2012-12-31 01:00:00   70.141261
6471  2012-12-31 02:00:00   50.594932
6472  2012-12-31 03:00:00   51.736104
6473  2012-12-31 04:00:00   15.401352
6474  2012-12-31 05:00:00   32.583631
6475  2012-12-31 06:00:00   35.310756
6476  2012-12-31 07:00:00   38.004516
6477  2012-12-31 08:00:00   12.674226
6478  2012-12-31 09:00:00   52.436760
6479  2012-12-31 10:00:00   40.220015
6480  2012-12-31 11:00:00   76.636474
6481  2012-12-31 12:00:00   90.378656
6482  2012-12-31 13:00:00  135.554204
6483  2012-12-31 14:00:00  141.374155
6484  2012-12-31 15:00:00  140.985685
6485  2012-12-31 16:00:00  124.879452
6486  2012-12-31 17:00:00  127.971455
6487  2012-12-31 18:00:00  126.020623
6488  2012-12-31 19:00:00   86.644841
6489  2012-12-31 20:00:00   86.644841
6490  2012-12-31 21:00:00   80.706123
6491  2012-12-31 22:00:00   95.627223
6492  2012-12-31 23:00:00   68.115707

[6493 rows x 2 columns]

In [ ]:
result.to_csv("./submission_20150714.csv",index=False)